version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3010 -b '0.0.0.0'
    volumes:
      - .:/one21-cms
    ports:
      - "3010:3010"
    depends_on:
      - db
