version: '3'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  web:
    build: .
    command: bundle exec rails s -p 3010 -b '0.0.0.0'
    volumes:
      - .:/one21-cms
    ports:
      - "3010:3010"
    depends_on:
      - db
